---
postgresql_image: "postgres:16-alpine"
postgresql_container_name: "postgres_db"
postgresql_container_port: "5432:5432"
postgresql_data_device: "/dev/oracleoci/oraclevdb"
postgresql_data_mount_point: "/var/lib/postgresql/data"
postgresql_db_name: "appdb"
postgresql_db_user: "appuser"
postgresql_db_password: "change-me-in-vault"
postgresql_container_restart_policy: "always"
