services:
  vault:
    build:
      context: ./docker_srcs/vault
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    secrets:
      - postgres_prod_user
      - postgres_prod_password
      - postgres_prod_host
      - postgres_prod_port
      - postgres_prod_database
      - postgres_dev_user
      - postgres_dev_password
      - postgres_dev_host
      - postgres_dev_port
      - postgres_dev_database
      - sendgrid_api_key
      - sendgrid_from_email
    networks:
      - backend_net
    restart: unless-stopped

  nginx:
    build:
      context: ./docker_srcs/nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./docker_srcs/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker_srcs/nginx/modsecurity/modsecurity.conf:/etc/nginx/modsecurity/modsecurity.conf
    networks:
      - backend_net
    restart: unless-stopped

networks:
  backend_net:
    driver: bridge

secrets:
  postgres_prod_user:
    file: ./secrets/vault/postgres_prod_user.txt
  postgres_prod_password:
    file: ./secrets/vault/postgres_prod_password.txt
  postgres_prod_host:
    file: ./secrets/vault/postgres_prod_host.txt
  postgres_prod_port:
    file: ./secrets/vault/postgres_prod_port.txt
  postgres_prod_database:
    file: ./secrets/vault/postgres_prod_database.txt
  postgres_dev_user:
    file: ./secrets/vault/postgres_dev_user.txt
  postgres_dev_password:
    file: ./secrets/vault/postgres_dev_password.txt
  postgres_dev_host:
    file: ./secrets/vault/postgres_dev_host.txt
  postgres_dev_port:
    file: ./secrets/vault/postgres_dev_port.txt
  postgres_dev_database:
    file: ./secrets/vault/postgres_dev_database.txt
  sendgrid_api_key:
    file: ./secrets/vault/sendgrid_api_key.txt
  sendgrid_from_email:
    file: ./secrets/vault/sendgrid_from_email.txt
