---
# 1. Limpa a pasta antiga para não sobrar arquivos duplicados ou quebrados
- name: Limpar diretório antigo do servidor
  ansible.builtin.file:
    path: /opt/docker_srcs
    state: absent

# 2. Recria a pasta do zero
- name: Criar diretório de destino da aplicação
  ansible.builtin.file:
    path: /opt/docker_srcs
    state: directory
    mode: '0755'

# 3. Copia os arquivos. ATENÇÃO absoluta à barra (/) no final do src!
- name: Copiar a pasta docker_srcs para o servidor
  ansible.builtin.copy:
    src: "{{ playbook_dir }}/../../docker_srcs/" 
    dest: /opt/docker_srcs/
    mode: '0755'


- name: Criar diretórios de secrets (Postgres, Vault, etc)
  ansible.builtin.file:
    path: "/opt/docker_srcs/secrets/{{ item }}"
    state: directory
    mode: '0700'
  loop:
    - postgres
    - vault

- name: Injetar arquivos de secrets do PostgreSQL
  ansible.builtin.copy:
    dest: "/opt/docker_srcs/secrets/postgres/{{ item.arquivo }}.txt"
    content: "{{ item.conteudo }}"
    mode: '0600'
  loop:
    - { arquivo: 'postgres_db', conteudo: 'postgres' }
    - { arquivo: 'postgres_user', conteudo: 'admin' }
    - { arquivo: 'postgres_password', conteudo: 'admin' }
    - { arquivo: 'postgres_init_db_args', conteudo: '-c log_statement=ddl -c log_min_duration_statement=1000'}

- name: Injetar arquivos de secrets do Vault
  ansible.builtin.copy:
    dest: "/opt/docker_srcs/secrets/vault/{{ item.arquivo }}.txt"
    content: "{{ item.conteudo }}"
    mode: '0600'
  loop:
    - { arquivo: 'postgres_prod_user', conteudo: 'postgres_user_prod' }
    - { arquivo: 'postgres_prod_password', conteudo: 'postgres_pass_prod_secure_123' }
    - { arquivo: 'postgres_prod_host', conteudo: 'postgres' }
    - { arquivo: 'postgres_prod_port', conteudo: '5432' }
    - { arquivo: 'postgres_prod_database', conteudo: 'app_db' }
    - { arquivo: 'postgres_dev_user', conteudo: 'dev_user' }
    - { arquivo: 'postgres_dev_password', conteudo: 'dev_password_123' }
    - { arquivo: 'postgres_dev_host', conteudo: 'postgres' }
    - { arquivo: 'postgres_dev_port', conteudo: '5432' }
    - { arquivo: 'postgres_dev_database', conteudo: 'app_db_dev' }
    - { arquivo: 'sendgrid_api_key', conteudo: 'SG.seu_sendgrid_api_key_aqui' }
    - { arquivo: 'sendgrid_from_email', conteudo: 'seu_email@dominio.com' }

- name: Fazer o build e subir os containers (Nginx, Postgres, Vault)
  community.docker.docker_compose_v2:
    project_src: /opt/docker_srcs
    build: always
    state: present