FROM owasp/modsecurity-crs:nginx-alpine

RUN apk add --no-cache curl \
    net-tools \
    wget \
    openssl \

COPY nginx.conf /etc/nginx/nginx.conf
COPY modsecurity/modsecurity.conf /etc/nginx/modsecurity/modsecurity.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]