---
- name: Preparar todos os servidores
  hosts: all
  become: true
  roles:
    - base

- name: Subir a stack de aplicações (Nginx, Postgres, Vault)
  hosts: database
  become: true
  roles:
    - docker
    - app_stack

- name: Preparar nós Kubernetes
  hosts: kubernetes
  become: true
  roles:
    - kubernetes
